SELECT --LISTAGG(DISTINCT L1.TEXTLINE, ' ') WITHIN GROUP(ORDER BY L1.LINENUMBER) AS SAMPLE_OPMERKING, 
LISTAGG(DISTINCT L2.TEXTLINE, ' ') WITHIN GROUP(ORDER BY L2.LINENUMBER) AS RESULT_OPMERKING,  LISTAGG(DISTINCT L3.TEXTLINE, ' ') WITHIN GROUP(ORDER BY L3.LINENUMBER) AS TEST_OPMERKING,
F.CODE MONSTERPUNTCODE, A.NAME NAAM, H.CODE PROJECTCODE, I.DESCRIPTION PROJECT_OMSCHRIJVING, A.CODE LABNUMMER, A.SAMPLINGDATE, B.CODE TESTCODE, B.RUNNR, B.STATUS TESTSTATUS, C.ELEMENTCODE, C.RAWRESULT RESULTAAT, C.ROUNDRESULT RESULTAAT_AFGEROND, C.REFMESSAGE, C.REFVALUE, C.REFCONCLUSION, F.ID MEETPUNT_ID, C.MEASUREDATE, G.CODE SOORTWATER, J.HOEDANIGHEID HOEDNHD, A.ID SAMPLE_ID, B.ID SAMPLE_TEST_ID, C.ID SAMPLE_RESULT_ID

FROM QMP.SAMPLE A,
--    LEFT JOIN QMP.NOTE K1 
--    ON (K1.OBJECTCLASSNAME  = 'Sample' AND K1.OBJECTID = A.ID)
--        LEFT JOIN QMP.NOTELINE L1 ON K1.ID = L1.NOTE_ID,   
QMP.SAMPLETEST B
    LEFT JOIN QMP.NOTE K3
    ON (K3.OBJECTCLASSNAME  = 'SampleTest' AND K3.OBJECTID =  B.ID)
        LEFT JOIN QMP.NOTELINE L3 ON K3.ID = L3.NOTE_ID, 
QMP.SAMPLERESULT C 
    LEFT JOIN QMP.NOTE K2
    ON (K2.OBJECTCLASSNAME  = 'SampleResult' AND K2.OBJECTID = C.ID)
        LEFT JOIN QMP.NOTELINE L2 ON  K2.ID = L2.NOTE_ID, 
QMP.V_ANALYSISGROUP D, QMP.PLANNEDSAMPLE E, QMP.SAMPLINGLOCATION F, QMP.SAMPLETYPE G, QMP.PROJECT H, QMP.PROJECTML I, QMP.SAMPLE_FL J

WHERE A.ID = B.SAMPLE_ID AND B.ID = C.SMPTST_ID AND B.CODE = D.TESTCODE AND A.ID = E.SAMPLE_ID AND E.SMPLLC_ID = F.ID AND A.SMPTP_ID = G.ID AND A.PROJ_ID = H.ID AND H.ID = I.ID AND I.LANCODE = 'NL' AND A.ID = J.ID
AND A.STATUS > 10 
AND A.ISCTRLSAMPLE = 0 
AND D.CODE = 200
AND F.STATUS = 40
AND B.STATUS > 100
AND C.MEASUREDATE >= add_months(trunc(sysdate), -12*2) --'01-01-2022'
AND F.CODE IN 
    (SELECT  AA.MONSTERPUNTCODE 
        FROM SAMPLE, ( SELECT DISTINCT A.CODE LABNUMMER, SUBSTR(A.SAMPLINGDATE, 1, 10) MONSTERNAMEDATUM, A.NAME OMSCHRIJVING, B.SMPLLC_CODE MONSTERPUNTCODE, B.HOEDANIGHEID HOEDNHD, A.STATUS, D.CODE FIATGROEP, MIN(C.STATUS) TEST_STATUS, E.CODE SMPL_PRIO, A.PRIOFINISHDATE 
        FROM SAMPLE A, SAMPLE_FL B, SAMPLETEST C, V_ANALYSISGROUP D, PRIORITYTYPE E, 
                        ( SELECT 200 AS GROUPNR   FROM DUAL) AA 
        WHERE A.ID = B.ID 
        AND A.ID = C.SAMPLE_ID 
        AND C.CODE = D.TESTCODE 
        AND A.PRIOTP_ID = E.ID 
        AND A.ISCTRLSAMPLE = 0 
        AND A.CODE NOT LIKE 'T%' 
        AND A.STATUS > 10 
        AND A.STATUS < 300 
        AND NVL(B.WGSSTATUS, 0) <> 294 
        AND D.CODE BETWEEN DECODE(GROUPNR, '' , 0, GROUPNR) 
        AND DECODE(GROUPNR, '' , 10000, GROUPNR) 
    GROUP BY A.CODE, SUBSTR(A.SAMPLINGDATE, 1, 10), A.NAME, B.SMPLLC_CODE, B.HOEDANIGHEID, A.STATUS, D.CODE, E.CODE, A.PRIOFINISHDATE) AA, CUSTOMER AB 
            WHERE SAMPLE.CODE = AA.LABNUMMER 
            AND SAMPLE.CUST_ID = AB.ID 
            AND (AA.TEST_STATUS > 210 
            AND AA.TEST_STATUS <= 270)) 
            
GROUP BY F.CODE, A.NAME, H.CODE, I.DESCRIPTION, A.CODE, 
A.SAMPLINGDATE, B.CODE, B.RUNNR, B.STATUS, C.ELEMENTCODE, 
C.RAWRESULT, C.ROUNDRESULT, C.REFMESSAGE, C.REFVALUE, C.REFCONCLUSION, 
F.ID, C.MEASUREDATE, G.CODE, J.HOEDANIGHEID, A.ID, 
B.ID, C.ID     
ORDER BY A.SAMPLINGDATE DESC;  